<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
 * Pagination Config Bootstrap 3 CSS Style
 * harviacode.com
 */

$config['query_string_segment'] = 'start';

$config['full_tag_open'] = '<ul class="pagination">';
$config['full_tag_close'] = '</ul>';

$config['first_link'] = '<i class="material-icons">first_page</i>';
$config['first_tag_open'] = '<li class="hoverable">';
$config['first_tag_close'] = '</li>';

$config['last_link'] = '<i class="material-icons">last_page</i>';
$config['last_tag_open'] = '<li class="hoverable">';
$config['last_tag_close'] = '</li>';

$config['next_link'] = '<i class="material-icons hoverable">chevron_right</i>';
$config['next_tag_open'] = '<li>';
$config['next_tag_close'] = '</li>';

$config['prev_link'] = '<i class="material-icons hoverable">chevron_left</i>';
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '</li>';

$config['cur_tag_open'] = '<li class="btn-floating waves-effect blue darken-2"><a class="white-text text-lighten-5">';
$config['cur_tag_close'] = '</a></li>';

$config['num_tag_open'] = '<li class="hoverable">';
$config['num_tag_close'] = '</li>';


/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-27 14:08:27 */
/* http://harviacode.com */
